### ISSUE TITLE
outdated README

### ISSUE THREAD

**Issue by mariusa** [jedisct1/as-wasi#131]
How to use console (eg Console.readAll) without `import "wasi"` , which is no longer supported?
https://github.com/AssemblyScript/wasi-shim#usage

**Comment by jedisct1** [comment]
I have no idea, since I don't use AssemblyScript any more.

But a PR to update the README would be welcome :)

**Comment by mariusa** [comment]
I see. I'm just trying to compile a .ts script to .wasm
Is AssemblyScript required for that? (asc compiler)
Or what could one use instead?

**Comment by jedisct1** [comment]
AssemblyScript is actually a different language, so you generally can't use it to compile TypeScript code.

There are no TypeScript to WebAssembly compilers. The way to run JavaScript in a pure WebAssembly environment is to use a Javascript runtime such as QuickJS, itself compiled to WebAssembly. The result is pretty slow, though.

So, in order to generate WebAssembly modules, especially with WASI, your best bet is to use Swift, Rust or Zig.

**Comment by mariusa** [comment]
Merci for clarification, Frank. I am using AssemblyScript indeed, that code is written into a .ts file (that's what a tutorial used). It works fine with AssemblyScript 0.20 and as-wasi. Then usage changed in AssemblyScript 0.21+ , trying to get it working again.

Appreciate your time
